INSERT INTO stories (name, user_id, content) VALUES ('Just My Luck', 2, 'You''ll never guess what happened last night! I am still in disbelief about the whole matter. Never in my 25 years of life on this earth, did I ever think this could happen to me. I feel like I should just go buy a bunch of lottery tickets, that is how lucky I feel.');
INSERT INTO stories (name, user_id, content) VALUES ('My Tennessee Story', 3, 'There is an old saying in Tennessee - I know it is in Texas, probably in Tennessee - that says, fool me once, shame on - shame on you. Fool me - you can not get fooled again. However... ');
INSERT INTO stories (name, user_id, content) VALUES ('The New York Crimes', 4, 'One piece of advice I wish I listened to, is do not live in New York. It is fine for a weekend trip or just going through the city but living htere is another story. I was blinded by the paycheque and ignored all the advice I was given. You know what I learned about New York?');


INSERT INTO stories (name, content, user_id, is_complete) VALUES ('A SUPER Original Story', 'This is the start of my original story. This is the end of my original story.', 2, true);
INSERT INTO stories (name, content, user_id, is_complete) VALUES ('The Cutie Bear', 'Once upon a time...there was a very cute bear. And then it died.', 3, true);
INSERT INTO stories (name, content, user_id, is_complete) VALUES ('Ribbit Life', 'There once was a frog named Bob. Who''s eyes were fragile and odd. He looked left and right, and started to fright. Then his eyes rolled into the pond.', 1, true);
INSERT INTO stories (name, content, user_id, is_complete) VALUES ('GO TEAM!', 'This project is awesome. Because we''re awesome. End of story.', 4, true);
INSERT INTO stories (name, content, user_id, is_complete) VALUES ('Greendale', '¿Dónde está la biblioteca? Me llamo T-Bone La araña discoteca Discoteca, muñeca, la biblioteca Es en bigote grande, perro, manteca Manteca, bigote, gigante, pequeño Cabeza es nieve Cerveza es bueno Buenos días, me gustas papas frías Bigote de la cabra Es Cameron Díaz Yeah boy, boy Yeah What! It''s 2009 Word', 4, true);
INSERT INTO stories (name, content, user_id, is_complete) VALUES ('Story 3', 'If we could live in this moment And just hold it Keep my head on your chest I''ll never leave this bed The flowers will be blooming The leaves will be turning And snow will be falling While we''re making love And the sun will be shining The flowers still are blooming Then leaves will turn again', 3, true);
INSERT INTO stories (name, content, user_id, is_complete) VALUES ('Truth', 'Truth is I''m dishonest ''Cause I''m always scared to get too deep Truth is that I want this ''Cause I always see you in my sleep Truth is that I love you, mm Even when I''m trying not to', 2, true);
INSERT INTO stories (name, content, user_id, is_complete) VALUES ('Messages to her', 'If we could live in this moment And just hold it Keep my head on your chest I''ll never leave this bed The flowers will be blooming The leaves will be turning And snow will be falling While we''re making love And the sun will be shining The flowers still are blooming Then leaves will turn again', 1, true);
INSERT INTO stories (name, user_id, content) VALUES ('Suburban Mystery', 1, 'Twas a dark and stormy night. I was walking home from work after a long shift and decided to take a shortcut home. That was my first mistake. As I turned unto the next street, I could feel a cold shiver run down my spine. I had to look behind, I just had to.');



