INSERT INTO story_snippet_options (contributor_id, story_snippet_text, story_id) VALUES (2, 'And thus endeth my tale.', 1);
INSERT INTO story_snippet_options (contributor_id, story_snippet_text, story_id) VALUES (3, 'BUT. THEN.', 1);
INSERT INTO story_snippet_options (contributor_id, story_snippet_text, story_id) VALUES (4, 'And then it stopped raining.', 1);
INSERT INTO story_snippet_options (contributor_id, story_snippet_text, story_id) VALUES (1, '...or maybe you can because nothing happened.', 2);
INSERT INTO story_snippet_options (contributor_id, story_snippet_text, story_id) VALUES (3, 'It still shakes me up...', 2);
INSERT INTO story_snippet_options (contributor_id, story_snippet_text, story_id) VALUES (4, 'Someone STOLE MY PIZZA!!!!!', 2);
INSERT INTO story_snippet_options (contributor_id, story_snippet_text, story_id) VALUES (5, 'Please don''t tell anyone, but...', 2);
INSERT INTO story_snippet_options (contributor_id, story_snippet_text, story_id) VALUES (1, 'Because I talk SO slowly', 3);
INSERT INTO story_snippet_options (contributor_id, story_snippet_text, story_id) VALUES (2, 'No?', 3);
INSERT INTO story_snippet_options (contributor_id, story_snippet_text, story_id) VALUES (4, 'Because you forgot to speed up this Podcast', 3);
INSERT INTO story_snippet_options (contributor_id, story_snippet_text, story_id) VALUES (5, 'You just won''t let me finish talking, will you...', 3);
INSERT INTO story_snippet_options (contributor_id, story_snippet_text, story_id) VALUES (3, 'This is an option that won''t get approved.', 4);
INSERT INTO story_snippet_options (contributor_id, story_snippet_text, story_id) VALUES (3, 'The end.', 4);
INSERT INTO story_snippet_options (contributor_id, story_snippet_text, story_id) VALUES (3, 'This is the end of my original story.', 5);
INSERT INTO story_snippet_options (contributor_id, story_snippet_text, story_id) VALUES (4, 'There was a very cute bear. And then it died.', 6);
INSERT INTO story_snippet_options (contributor_id, story_snippet_text, story_id) VALUES (1, 'Who''s eyes were fragile and odd. He looked left and right, and started to fright. Then his eyes rolled into the pond.', 7);
INSERT INTO story_snippet_options (contributor_id, story_snippet_text, story_id) VALUES (2, 'He looked left and right, and started to fright. Then his eyes rolled into the pond.', 7);
INSERT INTO story_snippet_options (contributor_id, story_snippet_text, story_id) VALUES (1, 'Then his eyes rolled into the pond.', 7);
INSERT INTO story_snippet_options (contributor_id, story_snippet_text, story_id) VALUES (2, 'Because we''re awesome. End of story.', 8);
