DROP TABLE IF EXISTS story_drafts CASCADE;

CREATE TABLE story_drafts (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  content TEXT
  );
